window.GLOSS = [
  // ── COMPLEX ANALYSIS ──
  {key:"argand-plane",title:"Argand Plane",level:"ug",def:"The 2D coordinate plane where complex numbers are plotted. The horizontal axis is the real part, the vertical axis the imaginary part. Named after Jean-Robert Argand (1806); equivalently called the complex plane or ℂ.",related:["Euler's Formula","Conformal Maps","Holomorphic Maps"]},
  {key:"eulers-formula",title:"Euler's Formula",level:"ug",def:"e^(iθ) = cos θ + i sin θ. Complex exponentials trace circles in the Argand plane. Setting θ = π gives Euler's identity e^(iπ) + 1 = 0 — connecting e, i, π, 1, and 0, the five most fundamental constants in mathematics.",related:["Argand Plane","Conformal Maps","Wavefunctions"]},
  {key:"conformal-maps",title:"Conformal Maps",level:"grad",def:"Angle-preserving transformations of the complex plane. A holomorphic function f(z) is conformal wherever f′(z) ≠ 0. Classic examples: z², 1/z, e^z. Fundamental in fluid dynamics, cartography, and the construction of Riemann surfaces.",related:["Holomorphic Maps","Riemann Surfaces","Argand Plane"]},
  {key:"holomorphic-maps",title:"Holomorphic Maps",level:"grad",def:"Complex functions that are complex-differentiable everywhere in their domain, satisfying the Cauchy–Riemann equations. A holomorphic function is \"rigid\": its values on any open set determine it everywhere via analytic continuation — far stronger than real differentiability.",related:["Conformal Maps","Contour Integration","Branch Cuts"]},
  {key:"contour-integration",title:"Contour Integration",level:"grad",def:"Evaluating integrals of complex functions along paths (contours) in ℂ. Cauchy's theorem: deforming the contour leaves the integral unchanged if no poles are crossed. The residue theorem converts hard real integrals into sums of residues — a central technique in physics.",related:["Holomorphic Maps","Riemann Surfaces","Branch Cuts"]},
  {key:"riemann-surfaces",title:"Riemann Surfaces",level:"grad",def:"Multi-sheeted surfaces making multi-valued complex functions (√z, log z) globally single-valued. The Riemann surface of √z is a two-sheeted surface glued along a branch cut — topologically an infinite cylinder. Riemann surfaces are compact 1D complex manifolds classified by genus g.",related:["Branch Cuts","Monodromy","Genus"]},
  {key:"branch-cuts",title:"Branch Cuts",level:"grad",def:"A curve in ℂ across which a multi-valued function (log z, z^α) is defined to be discontinuous, making it single-valued on the cut plane. The choice of cut is conventional; the Riemann surface is the natural global object encoding all sheets simultaneously.",related:["Riemann Surfaces","Monodromy","Domain Coloring"]},
  {key:"monodromy",title:"Monodromy",level:"grad",def:"The transformation a function undergoes when its argument traverses a closed loop encircling a branch point. For √z, one circuit maps √z → −√z. Monodromy groups classify the multi-valuedness of algebraic functions and appear in the theory of differential equations.",related:["Branch Cuts","Riemann Surfaces","Fundamental Group"]},
  {key:"domain-coloring",title:"Domain Coloring",level:"ug",def:"A visualization of f: ℂ → ℂ where hue encodes arg(f(z)) and brightness encodes |f(z)|. Zeros appear as points where all hues converge; poles as color explosions. Branch cuts show as hue discontinuities. Makes the analytic structure of complex functions immediately visible.",related:["Holomorphic Maps","Riemann Hypothesis","Branch Cuts"]},
  {key:"complex-iteration",title:"Complex Iteration",level:"ug",def:"Applying a map repeatedly: z₀, f(z₀), f(f(z₀)), …. For f(z) = z² + c, each orbit either stays bounded (z is in the Mandelbrot/filled Julia set) or escapes to infinity. The boundary between these fates is a fractal Julia curve — or the Mandelbrot boundary itself.",related:["Fractal Geometry","Orbit Visualizer","Phase Space"]},
  {key:"fractal-geometry",title:"Fractal Geometry",level:"ug",def:"Structures with self-similar detail at all scales and typically non-integer Hausdorff dimension. The Mandelbrot boundary has dimension ≈ 2 (Shishikura 1998); coastlines ~1.25; the Sierpiński triangle log 3/log 2 ≈ 1.585. Developed by Benoit Mandelbrot in the 1970s.",related:["Complex Iteration","Lyapunov Exponent","Strange Attractors"]},
  {key:"orbit-visualizer",title:"Orbit Visualizer",level:"ug",def:"A display showing how the sequence z₀, z₁ = f(z₀), z₂ = f(z₁), … moves through ℂ under iteration. Orbits that escape are colored by escape speed; bounded orbits mark the filled Julia set. Reveals the local dynamics — fixed points, cycles, and their basins.",related:["Complex Iteration","Fractal Geometry","Phase Space"]},
  {key:"riemann-hypothesis",title:"Riemann Hypothesis",level:"res",def:"The 1859 conjecture that all non-trivial zeros of ζ(s) lie on the critical line Re(s) = 1/2. It implies the sharpest known prime counting bounds: π(x) = Li(x) + O(√x log x). One of the seven Millennium Prize Problems ($1M reward). Unproven after 165 years of effort.",related:["Euler Product","Domain Coloring","Riemann Surfaces"]},
  {key:"euler-product",title:"Euler Product",level:"grad",def:"The identity ζ(s) = ∏_{p prime}(1−p^{−s})^{−1} for Re(s) > 1, encoding the fundamental theorem of arithmetic analytically. Each prime contributes one factor. The analytic continuation of ζ and the Riemann hypothesis concern the zeros of this product.",related:["Riemann Hypothesis","Domain Coloring","Complex Iteration"]},

  // ── GEOMETRY ──
  {key:"poincare-disk",title:"Poincaré Disk",level:"ug",def:"A model of hyperbolic geometry inside the unit disk where geodesics (\"straight lines\") are circular arcs meeting the boundary at right angles. Congruent triangles near the center appear much larger than those at the edge — the metric is distorted. The basis of Escher's Circle Limit woodcuts.",related:["Hyperbolic Triangle","{p,q} Tessellations","Riemann Surfaces"]},
  {key:"hyperbolic-triangle",title:"Hyperbolic Triangle",level:"ug",def:"A triangle in hyperbolic space whose angle sum is strictly less than π. The angular deficit π − (α+β+γ) equals the area of the triangle (times |κ|). Infinite hyperbolic triangles (with all angles = 0) tile the Poincaré disk — Escher's Circle Limit III is based on {8,3}.",related:["Poincaré Disk","{p,q} Tessellations","Gaussian Curvature"]},
  {key:"tessellations",title:"{p,q} Tessellations",level:"grad",def:"Tilings where regular p-gons meet q at each vertex. The condition 1/p + 1/q determines the geometry: = 1/2 → Euclidean ({4,4},{3,6},{6,3}); > 1/2 → spherical (Platonic solids); < 1/2 → hyperbolic (infinitely many tilings, all fitting in the Poincaré disk).",related:["Poincaré Disk","Hyperbolic Triangle","Aperiodic Tiling"]},
  {key:"aperiodic-tiling",title:"Aperiodic Tiling",level:"ug",def:"A tiling that covers the plane without translational repetition. Penrose tilings (P2 kite/dart, P3 rhombus) are the canonical example — any finite region appears infinitely often, yet no global period exists. The tiles have matching rules that enforce aperiodicity.",related:["Golden Ratio","5-fold Symmetry","{p,q} Tessellations"]},
  {key:"golden-ratio",title:"Golden Ratio",level:"ug",def:"φ = (1+√5)/2 ≈ 1.618. The unique positive solution to φ² = φ+1. Appears as the ratio of Penrose rhombus diagonals to sides, in regular pentagons (diagonal/side = φ), in Fibonacci sequences (lim aₙ₊₁/aₙ = φ), and in biological spiral phyllotaxis.",related:["Aperiodic Tiling","5-fold Symmetry","Fractal Geometry"]},
  {key:"5fold-symmetry",title:"5-fold Symmetry",level:"ug",def:"Rotational symmetry under 72° rotations. Forbidden for periodic crystal lattices by crystallographic restriction (only 1,2,3,4,6-fold allowed). Yet Penrose tilings have statistical 5-fold symmetry, foreshadowing Shechtman's 1984 discovery of quasicrystals (2011 Nobel in Chemistry).",related:["Aperiodic Tiling","Golden Ratio","{p,q} Tessellations"]},
  {key:"genus",title:"Genus",level:"grad",def:"The number of handles (through-holes) of a closed orientable surface: sphere g=0, torus g=1, pretzel g=2. The Euler characteristic χ = 2−2g; the Gauss–Bonnet theorem ∫κ dA = 2πχ. Riemann surfaces of genus g are compact 1D complex manifolds with g independent holomorphic 1-forms.",related:["Riemann Surfaces","Betti Numbers","Monodromy"]},

  // ── FOURIER / WAVES ──
  {key:"frequency-analysis",title:"Frequency Analysis",level:"ug",def:"Decomposing a signal into sinusoidal components — a Fourier transform. |F̂(ω)|² is the power spectrum. Central to signal processing, acoustics, optics, MRI, and quantum mechanics (momentum is the Fourier conjugate of position). The fast Fourier transform (FFT) makes it computationally practical.",related:["Epicycles","Gibbs Phenomenon","Wavefunctions"]},
  {key:"epicycles",title:"Epicycles",level:"ug",def:"Circular motions stacked atop each other. Ptolemy used epicycles for planetary orbits; Fourier analysis shows any periodic path is exactly a superposition of rotating circles (epicycles) at different radii and speeds. The discrete Fourier transform is literally the decomposition into N epicycles.",related:["Frequency Analysis","Gibbs Phenomenon","Complex Iteration"]},
  {key:"gibbs-phenomenon",title:"Gibbs Phenomenon",level:"ug",def:"A persistent ~8.9% overshoot at jump discontinuities when truncating a Fourier series at N terms, regardless of N. Named after Gibbs (1899), noticed by Wilbraham in 1848. Shows Fourier series converge pointwise but not uniformly near discontinuities.",related:["Frequency Analysis","Epicycles","Wavefunctions"]},
  {key:"chirp-waveform",title:"Chirp Waveform",level:"grad",def:"A gravitational wave signal from a binary inspiral: frequency and amplitude both increase as the bodies spiral inward, ending abruptly at merger. The chirp mass ℳ = (m₁m₂)^{3/5}/(m₁+m₂)^{1/5} determines the waveform evolution and is the best-measured parameter in GW astronomy.",related:["LIGO","Frequency Analysis","EM Waves"]},

  // ── LIE GROUPS / SPIN ──
  {key:"so3-su2",title:"SO(3) & SU(2)",level:"grad",def:"SO(3) = 3D rotation group (3×3 real orthogonal matrices, det=+1). SU(2) = 2×2 complex unitary matrices with det=1. They share the same Lie algebra su(2), but SU(2) is a 2-to-1 covering group of SO(3). This double-cover is why spinors need 720° to return to their original state.",related:["Bloch Sphere","Plate Trick","2-Spinors"]},
  {key:"bloch-sphere",title:"Bloch Sphere",level:"grad",def:"A unit sphere representing all pure states of a qubit (two-level quantum system). North/south poles are |0⟩ and |1⟩; the equator is linear superpositions. Mixed states fill the interior. Quantum gates are rotations of the Bloch sphere. Mathematically identical to the Riemann sphere ℂP¹.",related:["SO(3) & SU(2)","Wavefunctions","Poincaré Sphere (Optics)"]},
  {key:"plate-trick",title:"Plate Trick (Dirac Belt)",level:"grad",def:"Rotating a plate through 360° introduces a twist in the attached arm; a 720° rotation returns it to normal — a physical demonstration that π₁(SO(3)) = ℤ₂. Equivalently, SU(2) has a non-contractible loop at 360°. This is why electrons are spinors and must rotate 720° to return to their original quantum state.",related:["SO(3) & SU(2)","2-Spinors","Spinor Flag"]},
  {key:"2-spinors",title:"2-Spinors (Penrose)",level:"res",def:"2-component complex objects transforming under SL(2,ℂ) — the double cover of the Lorentz group. A 4-vector decomposes as κ^{AA′} = κ^A κ̄^{A′}. This formalism is adapted to the conformal structure of spacetime and is the natural language for twistor theory and Newman–Penrose formalism.",related:["SO(3) & SU(2)","Spinor Flag","Twistor Space"]},
  {key:"spinor-flag",title:"Spinor Flag",level:"res",def:"Penrose's geometric picture of a 2-spinor: a half-line (flagpole, giving a null direction in spacetime) with an attached half-plane (the flag, encoding the phase). A 360° rotation flips the flag; 720° restores it. Geometrizes the double-cover of SO(3) by SU(2) in an intuitive way.",related:["2-Spinors","Plate Trick","Rotors"]},
  {key:"spin-weighted-harmonics",title:"Spin-Weighted Spherical Harmonics",level:"res",def:"Generalizations of Yₗₘ for fields of spin-weight s on S². Scalars use s=0; electromagnetic fields use s=±1; gravitational waves use s=±2. Defined via the eth (ð) operator of Newman & Penrose. Essential for separating perturbation equations on Kerr backgrounds.",related:["2-Spinors","Petrov Types","Chirp Waveform"]},
  {key:"petrov-types",title:"Petrov Types",level:"res",def:"A classification of the Weyl curvature tensor by its principal null directions (PNDs). Type I: 4 distinct PNDs. Type D (Schwarzschild, Kerr): 2 double PNDs. Type N (plane waves): 1 quadruple PND. Type O: conformally flat. Named after Aleksei Petrov (1954).",related:["Weyl Curvature","Kerr Black Hole","2-Spinors"]},

  // ── SPECIAL & GENERAL RELATIVITY ──
  {key:"minkowski-diagram",title:"Minkowski Diagram",level:"ug",def:"A spacetime diagram with time vertical and space horizontal; light cones at 45°. Events, worldlines, and simultaneity hyperplanes become geometric objects. Invented by Hermann Minkowski (1908) to visualize Einstein's 1905 special relativity geometrically.",related:["Lorentz Boost","Twin Paradox","Penrose Diagram"]},
  {key:"lorentz-boost",title:"Lorentz Boost",level:"ug",def:"A coordinate transformation between two inertial frames with relative velocity v: t′ = γ(t−vx/c²), x′ = γ(x−vt), with γ = 1/√(1−v²/c²). Unlike Galilean boosts, it mixes space and time, leading to time dilation (moving clocks run slow) and length contraction.",related:["Minkowski Diagram","Twin Paradox","Chirality"]},
  {key:"twin-paradox",title:"Twin Paradox",level:"ug",def:"The traveling twin ages less than the stay-at-home twin — not a paradox, but a consequence of proper time τ = ∫√(1−v²/c²) dt. The traveling twin's worldline is shorter in spacetime (even though it is longer in space). The asymmetry is resolved by the traveling twin's acceleration.",related:["Minkowski Diagram","Lorentz Boost","Phase Space"]},
  {key:"penrose-diagram",title:"Penrose (Conformal) Diagram",level:"grad",def:"A conformal compactification mapping all of spacetime (including null/timelike infinity) into a finite bounded region while preserving causal structure — light always travels at 45°. Invented by Penrose to visualize the global causal structure of black holes, wormholes, and the Big Bang.",related:["Hawking Radiation","Kerr Black Hole","Weyl Curvature"]},
  {key:"hawking-radiation",title:"Hawking Radiation",level:"grad",def:"Black holes emit thermal radiation at temperature T = ℏc³/(8πGMk_B), derived using QFT in curved spacetime (Hawking 1974). Implies black holes slowly lose mass and eventually evaporate. Raises the black hole information paradox: is information preserved during evaporation?",related:["Penrose Diagram","Kerr Black Hole","Vacuum Energy"]},
  {key:"kerr-black-hole",title:"Kerr Black Hole",level:"grad",def:"Roy Kerr's 1963 exact solution to Einstein's equations for a rotating uncharged black hole. Unlike Schwarzschild, it has an outer and inner horizon, an ergosphere (frame-dragging region), a ring singularity, and — controversially — closed timelike curves near the singularity.",related:["Penrose Diagram","Hawking Radiation","Weyl Curvature"]},
  {key:"friedmann-equation",title:"Friedmann Equation",level:"grad",def:"(ȧ/a)² = 8πGρ/3 − k/a² + Λ/3. Derived from Einstein's equations assuming spatial homogeneity and isotropy (FLRW metric), it governs cosmic expansion. Here a(t) is the scale factor, ρ includes matter and radiation, k ∈ {−1,0,+1} is spatial curvature, and Λ is dark energy.",related:["Penrose Diagram","Weyl Curvature","CCC Aeons"]},
  {key:"weyl-curvature",title:"Weyl Curvature",level:"res",def:"The traceless part of the Riemann curvature tensor, encoding tidal distortions and gravitational-wave degrees of freedom (Ricci curvature is sourced by matter; Weyl is \"free\" gravitational field). Penrose's Weyl Curvature Hypothesis: the Big Bang has zero Weyl curvature, explaining the thermodynamic arrow of time.",related:["Penrose Diagram","Petrov Types","CCC Aeons"]},

  // ── QUANTUM MECHANICS ──
  {key:"wavefunctions",title:"Wavefunctions",level:"ug",def:"A complex-valued function ψ(x,t) encoding all information about a quantum state. |ψ|² is the probability density; ψ evolves via the Schrödinger equation iℏ∂ψ/∂t = Hψ. A measurement collapses ψ to an eigenstate; the coefficient squared gives the probability of that outcome.",related:["Uncertainty Principle","Bloch Sphere","Path Integral"]},
  {key:"uncertainty-principle",title:"Uncertainty Principle",level:"ug",def:"Heisenberg's inequality ΔxΔp ≥ ℏ/2. Position and momentum cannot be simultaneously precise — a fundamental property of wave packets (narrow in x → broad in k = p/ℏ), not a measurement artifact. Similar relations hold for energy–time (ΔEΔt ≥ ℏ/2) and other conjugate pairs.",related:["Wavefunctions","Stern–Gerlach","Vacuum Energy"]},
  {key:"stern-gerlach",title:"Stern–Gerlach Experiment",level:"ug",def:"Silver atoms shot through an inhomogeneous magnetic field (1922) split into exactly two spots — proving angular momentum (spin-½) is quantized in units of ℏ/2, not continuously distributed. The first direct evidence for a fully non-classical, intrinsically quantum property.",related:["Wavefunctions","Bloch Sphere","SO(3) & SU(2)"]},
  {key:"entanglement",title:"Quantum Entanglement",level:"grad",def:"A quantum correlation that cannot be explained by any local hidden-variable theory. In the Bell state (|00⟩+|11⟩)/√2, measuring qubit A instantly determines qubit B regardless of separation. Entanglement is a resource for quantum computing, quantum key distribution, and teleportation.",related:["CHSH Inequality","Entanglement Entropy","Teleportation"]},
  {key:"chsh-inequality",title:"CHSH Inequality",level:"grad",def:"A Bell inequality: |⟨AB⟩+⟨AB′⟩+⟨A′B⟩−⟨A′B′⟩| ≤ 2 for any local hidden-variable theory. QM can achieve 2√2 ≈ 2.83 (Tsirelson bound). Loophole-free experimental violations — by Aspect (1982), Hensen (2015), and Zeilinger et al. (2022 Nobel) — definitively rule out local realism.",related:["Entanglement","Teleportation","Bloch Sphere"]},
  {key:"teleportation",title:"Quantum Teleportation",level:"grad",def:"Transferring an unknown quantum state from A to B using prior entanglement + a 2-bit classical message. No faster-than-light signaling: the classical channel is required. Demonstrated over 1200 km by the Micius satellite and in fiber links exceeding 100 km.",related:["Entanglement","Micius Satellite","CHSH Inequality"]},
  {key:"micius-satellite",title:"Micius Satellite",level:"grad",def:"China's quantum science satellite (launched Aug 2016), used to distribute entangled photon pairs between ground stations 1200 km apart, demonstrate QKD (quantum key distribution) from space, and test Bell inequalities at intercontinental distances — the first satellite-based quantum communication experiments.",related:["Teleportation","Entanglement","CHSH Inequality"]},

  // ── CLASSICAL MECHANICS ──
  {key:"least-action",title:"Principle of Least Action",level:"ug",def:"The path taken by a physical system between two events is the one that makes the action S = ∫L dt stationary (δS = 0), where L = T − V is the Lagrangian. The Euler–Lagrange equations, Newton's laws, Maxwell's equations, and Einstein's equations all follow from this single variational principle.",related:["Phase Space","Symplectic Form","Path Integral"]},
  {key:"phase-space",title:"Phase Space",level:"ug",def:"The 2n-dimensional space of all states of a system with n degrees of freedom, with coordinates (q, p). A point completely specifies the state; trajectories evolve via Hamilton's equations and never cross. Liouville's theorem: phase-space volume is conserved under Hamiltonian flow.",related:["Least Action","Symplectic Form","Lyapunov Exponent"]},
  {key:"double-pendulum",title:"Double Pendulum",level:"ug",def:"A pendulum with a second one attached to its end. For small angles it is integrable (two normal modes); for large amplitudes it exhibits deterministic chaos — nearby initial conditions lead to exponentially diverging trajectories after a few oscillations. The standard pedagogical example of chaos in a conservative system.",related:["Phase Space","Lyapunov Exponent","Strange Attractors"]},
  {key:"symplectic-form",title:"Symplectic Form",level:"grad",def:"A closed non-degenerate 2-form ω on phase space. In Darboux coordinates ω = dqⁱ∧dpᵢ. Hamilton's equations, Poisson brackets, and Liouville's theorem all emerge from ω. Symplectic geometry is the geometric arena of Hamiltonian mechanics; it is preserved by canonical transformations.",related:["Phase Space","Least Action","Liouville–Arnold Tori"]},
  {key:"liouville-tori",title:"Liouville–Arnold Tori",level:"grad",def:"In a completely integrable Hamiltonian system with n degrees of freedom and n independent conserved quantities in involution, the phase space foliates into n-dimensional invariant tori (Liouville–Arnold theorem). Motion on each torus is quasiperiodic. KAM theory studies their fate under perturbations.",related:["Symplectic Form","KAM Theorem","KdV Solitons"]},
  {key:"kdv-solitons",title:"KdV Solitons",level:"grad",def:"Exact localized wave solutions to the Korteweg–de Vries equation (uₜ − 6uuₓ + uₓₓₓ = 0) that maintain their shape while propagating. Multiple solitons pass through each other intact, emerging unscathed. Discovered numerically by Zabusky & Kruskal (1965); solved exactly via the inverse scattering transform.",related:["Liouville–Arnold Tori","Symplectic Form","Phase Space"]},
  {key:"lyapunov-exponent",title:"Lyapunov Exponent",level:"grad",def:"The exponential rate λ at which nearby trajectories diverge: |δz(t)| ~ e^{λt}|δz(0)|. Positive λ defines chaos; the Lyapunov time 1/λ is how long reliable predictions last. For the double pendulum λ ≈ 1/few seconds; for the solar system λ ≈ 1/5 Myr.",related:["Strange Attractors","KAM Theorem","Phase Space"]},
  {key:"kam-theorem",title:"KAM Theorem",level:"grad",def:"Kolmogorov–Arnold–Moser (1954–63): most invariant tori of an integrable Hamiltonian system survive small perturbations if their frequencies are \"sufficiently irrational\" (Diophantine condition). Surviving tori act as barriers to Arnold diffusion. Explains why the solar system is stable over billions of years despite being mildly chaotic.",related:["Lyapunov Exponent","Liouville–Arnold Tori","Strange Attractors"]},
  {key:"strange-attractors",title:"Strange Attractors",level:"grad",def:"Fractal subsets of phase space to which dissipative chaotic systems are attracted. Trajectories exhibit sensitive dependence on initial conditions while remaining bounded. Non-integer Hausdorff dimension (Lorenz attractor: ~2.06). Named by Ruelle & Takens (1971); Lorenz discovered his attractor in 1963.",related:["Lyapunov Exponent","Fractal Geometry","Phase Space"]},

  // ── QUANTUM FIELD THEORY ──
  {key:"dirac-sea",title:"Dirac Sea",level:"grad",def:"Dirac's 1930 interpretation of negative-energy solutions: all negative-energy states are already filled. A hole in this sea is a positron — the first prediction of an antiparticle, confirmed by Carl Anderson (1932). Conceptually superseded by quantum field theory, but historically crucial.",related:["Pair Creation","Chirality","Feynman Diagrams"]},
  {key:"pair-creation",title:"Pair Creation",level:"grad",def:"Production of a particle–antiparticle pair (e.g., e⁻e⁺) from a photon (γ → e⁻e⁺ near a nucleus) or a strong field. Requires energy ≥ 2mc². In extreme fields (Schwinger limit E ≈ 1.3×10¹⁸ V/m), the vacuum itself spontaneously produces pairs — the Schwinger effect.",related:["Dirac Sea","Chirality","Vacuum Energy"]},
  {key:"chirality",title:"Chirality",level:"grad",def:"\"Handedness\" — a property distinguishing an object from its mirror image. In the Standard Model, left- and right-handed fermions transform differently: only left-handed participate in SU(2)_L weak interactions. Parity violation by the weak force (Wu, 1956) was one of the biggest surprises in 20th-century physics.",related:["Dirac Sea","U(1) Gauge","Gauge Theory"]},
  {key:"u1-gauge",title:"U(1) Gauge Symmetry",level:"grad",def:"The local phase symmetry ψ → e^{iα(x)}ψ underlying quantum electrodynamics (QED). Requiring invariance under this spacetime-dependent transformation forces the introduction of the photon as a gauge field Aμ with the minimal coupling ∂μ → ∂μ − ieAμ. The prototype for all gauge theories.",related:["Gauge Theory","Feynman Diagrams","Chirality"]},
  {key:"feynman-diagrams",title:"Feynman Diagrams",level:"grad",def:"Pictorial representations of terms in a Dyson perturbation expansion for QFT scattering amplitudes. Lines represent propagating particles (propagators); vertices represent interactions (coupling constants). Each diagram corresponds to a specific Feynman integral; summing all diagrams at a given loop order gives measurable cross-sections.",related:["Path Integral","Renormalization","Asymptotic Freedom"]},
  {key:"asymptotic-freedom",title:"Asymptotic Freedom",level:"res",def:"In QCD, the strong coupling αₛ decreases logarithmically at high energies (short distances): αₛ(μ) ≈ 2π/[b₀ log(μ/ΛQCD)]. Quarks inside protons are nearly free at short distances but permanently confined at long distances. Discovered independently by Gross, Politzer & Wilczek (2004 Nobel Prize).",related:["Feynman Diagrams","Renormalization","Particle Zoo"]},
  {key:"gauge-theory",title:"Gauge Theory",level:"grad",def:"A field theory invariant under local Lie group transformations G. Requiring local invariance forces the introduction of gauge boson fields (\"connections\"). The Standard Model is U(1)×SU(2)×SU(3); the photon, W/Z, and gluons are the gauge bosons. General relativity is a gauge theory of local Lorentz symmetry.",related:["U(1) Gauge","Feynman Diagrams","Higgs Mechanism"]},
  {key:"particle-zoo",title:"Particle Zoo",level:"ug",def:"The bewildering proliferation of hadrons discovered in the 1950s–60s — hundreds of apparently \"elementary\" particles. Gell-Mann organized them via SU(3) flavor symmetry (Eightfold Way), predicted the Ω⁻ (confirmed 1964), and introduced quarks to explain the zoo as bound states of three fundamental fermions.",related:["Eightfold Way","Higgs Mechanism","Feynman Diagrams"]},
  {key:"higgs-mechanism",title:"Higgs Mechanism",level:"grad",def:"W± and Z bosons acquire mass through spontaneous symmetry breaking (SSB) of SU(2)×U(1): the Higgs field gains a non-zero vacuum expectation value ⟨φ⟩ = v ≈ 246 GeV; gauge bosons \"eat\" three Goldstone bosons to gain longitudinal polarization and mass. The physical Higgs boson was confirmed at CERN in 2012 (2013 Nobel to Higgs & Englert).",related:["Gauge Theory","Particle Zoo","U(1) Gauge"]},
  {key:"path-integral",title:"Path Integral",level:"grad",def:"Feynman's formulation: the quantum propagator ⟨x_f|e^{−iHt/ℏ}|x_i⟩ = ∫𝒟x e^{iS[x]/ℏ} sums over all paths from xᵢ to x_f, each weighted by e^{iS/ℏ}. The stationary-phase approximation (ℏ→0) recovers classical mechanics. Generalizes to QFT as a functional integral over field configurations.",related:["Wavefunctions","Feynman Diagrams","Vacuum Energy"]},
  {key:"vacuum-energy",title:"Vacuum Energy",level:"grad",def:"In QFT, the ground state has non-zero energy from zero-point fluctuations of all fields: E_vac = Σ ℏω_k/2 (formally divergent). The cosmological constant problem: naïve estimates give ρ_vac ~10¹⁰⁰ J/m³, yet the observed value is ~10⁻⁹ J/m³ — a discrepancy of ~120 orders of magnitude. One of the deepest unsolved problems.",related:["Path Integral","Renormalization","Hawking Radiation"]},
  {key:"renormalization",title:"Renormalization",level:"grad",def:"Systematically absorbing UV (high-energy) divergences in QFT into redefined physical parameters (bare mass, charge, field strength). A theory is renormalizable if only finitely many counterterms are needed. QED (Feynman, Schwinger, Tomonaga — 1965 Nobel), QCD, and the Standard Model are all renormalizable.",related:["Feynman Diagrams","Vacuum Energy","Asymptotic Freedom"]},
  {key:"self-duality",title:"Self-Dual Gauge Fields",level:"res",def:"A Yang–Mills field F satisfying F = ★F (equal to its Hodge dual in 4D Euclidean space) is self-dual. Self-dual fields automatically satisfy the Yang–Mills equations and minimize the action in their topological sector. They appear as instantons — localized tunneling solutions in Euclidean spacetime.",related:["BPST Instanton","Atiyah–Singer Index Theorem","Symplectic Form"]},
  {key:"bpst-instanton",title:"BPST Instanton",level:"res",def:"The Belavin–Polyakov–Schwarz–Tyupkin instanton: a self-dual SU(2) Yang–Mills solution in Euclidean ℝ⁴ with topological charge Q=1. Instantons tunnel between topologically distinct QCD vacuum sectors. They contribute to the θ-vacuum, the strong CP problem, and have deep connections to the Atiyah–Singer index theorem.",related:["Self-Dual Gauge Fields","Atiyah–Singer Index Theorem","Asymptotic Freedom"]},

  // ── TOPOLOGY & ALGEBRA ──
  {key:"fundamental-group",title:"Fundamental Group",level:"grad",def:"π₁(X, x₀) = homotopy classes of loops based at x₀. Measures \"1-dimensional holes\": π₁(S¹) = ℤ; π₁(torus) = ℤ²; π₁(SO(3)) = ℤ₂ (double-cover, explaining the Plate Trick). Simply connected spaces have π₁ = {1}. The fundamental group is the first homotopy group; higher homotopy groups πₙ measure n-dimensional holes.",related:["Covering Spaces","Knot Theory","Plate Trick"]},
  {key:"covering-spaces",title:"Covering Spaces",level:"grad",def:"A covering space p: X̃ → X has the property that every point in X has a neighborhood evenly covered by disjoint homeomorphic sheets in X̃. The fundamental group π₁(X) acts freely and transitively on the sheets. The universal cover (p=∞ sheets) is simply connected. SU(2) is the universal cover of SO(3) with 2 sheets.",related:["Fundamental Group","Monodromy","SO(3) & SU(2)"]},
  {key:"knot-theory",title:"Knot Theory",level:"grad",def:"The study of embeddings of S¹ in S³, classified up to ambient isotopy. Knot invariants (Jones polynomial via quantum groups, HOMFLY polynomial, Khovanov homology) distinguish knots. Knot theory connects to topological quantum field theory (Chern–Simons theory), DNA topology, and statistical mechanics.",related:["Fundamental Group","Chern Classes","Covering Spaces"]},
  {key:"closed-vs-exact",title:"Closed vs Exact Forms",level:"grad",def:"A k-form ω is closed if dω = 0; exact if ω = dα for some (k−1)-form α. d²=0 means exact ⟹ closed; the failure of the converse is measured by de Rham cohomology H^k_dR = {closed}/{exact}. H^k_dR is a topological invariant equal (by de Rham's theorem) to the k-th cohomology with real coefficients.",related:["Betti Numbers","Chern Classes","Symplectic Form"]},
  {key:"betti-numbers",title:"Betti Numbers",level:"grad",def:"Topological invariants bₖ = rank H_k(X; ℤ), counting k-dimensional \"holes\": b₀ = connected components, b₁ = independent loops, b₂ = enclosed voids. Euler characteristic χ = Σ(−1)ᵏbₖ. For a surface of genus g: b₀=1, b₁=2g, b₂=1, χ=2−2g.",related:["Closed vs Exact Forms","Chern Classes","Genus"]},
  {key:"chern-classes",title:"Chern Classes",level:"grad",def:"Cohomological invariants cₖ(E) ∈ H²ᵏ(M,ℤ) of complex vector bundles. Appear in: the Atiyah–Singer index theorem; the IQHE (first Chern number = Hall conductance in units e²/h); anomaly cancellation in string theory; characteristic classes of gauge fields. Computed via the curvature 2-form.",related:["Betti Numbers","Closed vs Exact Forms","Berry Phase"]},
  {key:"atiyah-singer",title:"Atiyah–Singer Index Theorem",level:"res",def:"index(D) = ∫_M Â(M)·ch(E). Equates the analytical index of an elliptic differential operator D (dim ker D − dim coker D) to a topological integral over the manifold. Unifies: Gauss–Bonnet (D = d+d†), Riemann–Roch, Hirzebruch signature. Proved by Atiyah & Singer (1963); one of the deepest results in 20th-century mathematics.",related:["Chern Classes","BPST Instanton","Betti Numbers"]},
  {key:"root-systems",title:"Root Systems",level:"grad",def:"A finite set Φ of vectors in Euclidean space satisfying: (1) Φ spans; (2) reflections sₐ(β) = β − 2⟨β,α⟩/⟨α,α⟩·α ∈ Φ; (3) 2⟨β,α⟩/⟨α,α⟩ ∈ ℤ. They classify simple complex Lie algebras: Aₙ, Bₙ, Cₙ, Dₙ plus the 5 exceptional types E₆, E₇, E₈, F₄, G₂.",related:["Dynkin Diagrams","Eightfold Way","SO(3) & SU(2)"]},
  {key:"dynkin-diagrams",title:"Dynkin Diagrams",level:"grad",def:"Graphs encoding a root system: nodes are simple roots; edges encode angles between them (single/double/triple edges; arrows for asymmetric cases). The A-D-E diagrams (no multiple edges) have remarkable connections to Platonic solids, Du Val singularities, string theory, and extended supersymmetry.",related:["Root Systems","Eightfold Way","Atiyah–Singer Index Theorem"]},
  {key:"eightfold-way",title:"Eightfold Way",level:"grad",def:"Gell-Mann's 1961 organization of hadrons using the adjoint and fundamental representations of SU(3) flavor symmetry, grouping mesons into octets and baryons into octets/decuplets. It predicted the Ω⁻ baryon (confirmed 1964, 8-fold pattern complete) and led directly to the quark model.",related:["Root Systems","Particle Zoo","Gauge Theory"]},

  // ── GEOMETRIC ALGEBRA ──
  {key:"geometric-product",title:"Geometric Product",level:"grad",def:"The fundamental operation ab = a·b + a∧b of Clifford (geometric) algebra: inner product (scalar) plus outer product (bivector), united in a single associative product. Gives a complete algebraic framework for vectors, rotations, reflections, and spinors in any dimension without coordinates.",related:["Rotors","Spinor Flag","SO(3) & SU(2)"]},
  {key:"rotors",title:"Rotors (Clifford Algebra)",level:"grad",def:"A rotor R = exp(−θB̂/2) in Clifford algebra implements a rotation by angle θ in the plane of the unit bivector B̂: v ↦ RvR̃. A 360° rotation gives R = −1; 720° gives +1 — encoding spinor behavior. Quaternions are the rotors of ℝ³; Cl(3,1) rotors handle Lorentz transformations.",related:["Geometric Product","Spinor Flag","Plate Trick"]},

  // ── CONFORMAL FIELD THEORY ──
  {key:"virasoro-algebra",title:"Virasoro Algebra",level:"res",def:"Infinite-dimensional Lie algebra with generators Lₙ (n ∈ ℤ): [Lₙ,Lₘ] = (n−m)L_{n+m} + c(n³−n)δ_{n+m,0}/12, where c is the central charge. It is the symmetry algebra of 2D conformal field theories — the worldsheet of strings, critical statistical models (c=1/2 is the Ising model), and AdS₃/CFT₂.",related:["AdS/CFT","Entanglement Entropy","Riemann Surfaces"]},
  {key:"adscft",title:"AdS/CFT Correspondence",level:"res",def:"Maldacena's 1997 duality: type IIB string theory on AdS₅×S⁵ is equivalent to 𝒩=4 SU(N) super-Yang–Mills on the 4D boundary. The first concrete example of holography: bulk gravity ↔ boundary QFT. Widely used to study strongly coupled systems via tractable gravitational duals.",related:["Virasoro Algebra","Entanglement Entropy","Twistor Space"]},
  {key:"entanglement-entropy",title:"Entanglement Entropy",level:"res",def:"S_A = −Tr(ρ_A log ρ_A) where ρ_A = Tr_B ρ_AB is the reduced density matrix. Quantifies quantum entanglement between A and B. In holographic theories (AdS/CFT): S_A = Area(γ_A)/(4G_N) (Ryu–Takayanagi formula) — a minimal surface in the bulk. Connects information, geometry, and thermodynamics.",related:["Entanglement","AdS/CFT","Chern Classes"]},

  // ── TWISTORS ──
  {key:"twistor-space",title:"Twistor Space",level:"res",def:"Penrose's (1967) 4D complex space PT where: each point in Minkowski spacetime ↔ a Riemann sphere CP¹ in PT; each twistor (point in PT) ↔ a null geodesic (light ray) in spacetime. Encodes the conformal structure of spacetime; is the natural arena for massless particles.",related:["Penrose Transform","Amplituhedron","2-Spinors"]},
  {key:"penrose-transform",title:"Penrose Transform",level:"res",def:"An integral transform mapping solutions of massless free-field equations on spacetime (helicity h) to sheaf cohomology classes H¹(PT, 𝒪(−2h−2)) on twistor space. Translates PDE problems into purely geometric (sheaf-theoretic) data, and is the foundation for twistor-string theory.",related:["Twistor Space","Amplituhedron","Holomorphic Maps"]},
  {key:"amplituhedron",title:"Amplituhedron",level:"res",def:"A geometric object in the Grassmannian Gr(k,n) (Arkani-Hamed & Trnka, 2013) whose volume directly encodes scattering amplitudes in planar 𝒩=4 super-Yang–Mills theory, without ever referring to Feynman diagrams, spacetime, or unitarity. Suggests scattering amplitudes have a purely geometric origin.",related:["Twistor Space","Feynman Diagrams","Penrose Transform"]},

  // ── EM / EXPERIMENTAL ──
  {key:"field-lines",title:"Field Lines",level:"ug",def:"Curves everywhere tangent to a vector field. Electric field lines start at positive charges and end at negative; their density is proportional to |E|. Magnetic field lines form closed loops (∇·B = 0). Introduced by Michael Faraday as a physical intuition; formalized by Maxwell via flux and Gauss's law.",related:["EM Waves","Gauge Theory","U(1) Gauge"]},
  {key:"em-waves",title:"Electromagnetic Waves",level:"ug",def:"Mutually sustaining oscillations of E and B propagating at c = 1/√(ε₀μ₀). Maxwell's equations predict them (1865); Hertz confirmed them (1887). Light, radio, microwaves, X-rays, and γ-rays all obey E = hν and p = hν/c, differing only in frequency and hence quantum energy.",related:["Field Lines","LIGO","Chirp Waveform"]},
  {key:"ligo",title:"LIGO",level:"grad",def:"Laser Interferometer Gravitational-Wave Observatory — two L-shaped Michelson interferometers with 4 km arms (Hanford WA and Livingston LA). On Sept 14, 2015 at 09:50:45 UTC, GW150914 arrived: two ~30M☉ black holes merging at ~150 Mpc. The signal lasted 0.2 s, peak strain h ≈ 10⁻²¹. 2017 Nobel to Weiss, Thorne & Barish.",related:["Chirp Waveform","EM Waves","Frequency Analysis"]},
  {key:"laser-cooling",title:"Laser Cooling",level:"grad",def:"Slowing atoms using photon recoil: a laser tuned to ω₀ − δ (red-detuned) is Doppler-shifted onto resonance only for atoms approaching the beam, selectively absorbing photons and decelerating them. Achieves sub-Doppler temperatures (~μK) via polarization-gradient cooling; recoil limit ~240 nK for Rb-87.",related:["BEC","Optical Tweezers","Berry Phase"]},
  {key:"bec",title:"Bose–Einstein Condensate (BEC)",level:"grad",def:"When bosons are cooled below T_c = (n/ζ(3/2))^{2/3} ℏ²/(2πmk_B), a macroscopic fraction condenses into the single-particle ground state, forming a coherent quantum superfluid described by a macroscopic wavefunction ψ(r). First achieved in 1995 (87Rb — Cornell & Wieman; 23Na — Ketterle; 2001 Nobel Prize).",related:["Laser Cooling","Optical Tweezers","Wavefunctions"]},
  {key:"optical-tweezers",title:"Optical Tweezers",level:"grad",def:"A tightly focused laser beam traps dielectric particles via gradient force (∇|E|² pulls particles toward focus). Invented by Arthur Ashkin (2018 Nobel). Force resolution ~0.1 pN. Used to stretch DNA, measure kinesin stepping forces (~5 pN), trap single atoms in optical lattices for quantum simulation.",related:["Laser Cooling","BEC","Berry Phase"]},
  {key:"quantum-hall",title:"Quantum Hall Effect",level:"grad",def:"At low T and high B, the Hall conductance σ_H = νe²/h for ν ∈ ℤ (IQHE, von Klitzing 1985 Nobel) or ν ∈ ℚ (FQHE, Tsui–Störmer 1998 Nobel). The integer ν is a topological Chern number — quantized to extraordinary precision (~1 ppb) independent of disorder, making it the resistance standard.",related:["Berry Phase","Chern Classes","GMR"]},
  {key:"berry-phase",title:"Berry Phase",level:"grad",def:"A geometric phase γ = ∮ A·dR acquired by a quantum state when its Hamiltonian is adiabatically cycled around a closed loop C in parameter space. The Berry connection A = i⟨n|∇_R|n⟩ is a U(1) gauge field on parameter space; the Berry curvature ∇×A is analogous to a magnetic field.",related:["Quantum Hall Effect","Chern Classes","Holonomy"]},
  {key:"gmr",title:"Giant Magnetoresistance (GMR)",level:"grad",def:"In [FM/NM]ₙ multilayers, resistance drops dramatically (~50%) when adjacent ferromagnetic layers align. Spin-up/down electrons scatter differently in aligned vs anti-aligned stacks. Discovered independently by Fert and Grünberg (1988; 2007 Nobel Prize). Enabled 1000× increase in hard-disk capacity in the 1990s–2000s.",related:["Spintronics","Berry Phase","Quantum Hall Effect"]},
  {key:"spintronics",title:"Spintronics",level:"grad",def:"Electronics exploiting electron spin as an information carrier alongside charge. Key phenomena: GMR, spin-transfer torque (STT), spin–orbit torque (SOT), spin Hall effect, and tunneling magnetoresistance (TMR). Applications: MRAM, STT-oscillators, racetrack memory, and spin-based qubits.",related:["GMR","MRAM","Berry Phase"]},
  {key:"mram",title:"MRAM",level:"grad",def:"Magnetic Random-Access Memory: bits stored as magnetic orientations of magnetic tunnel junctions (MTJs). Read via tunneling magnetoresistance; written by spin-transfer torque (STT-MRAM at ~10 nm nodes) or spin-orbit torque (SOT-MRAM for higher endurance). Non-volatile, ~ns latency, unlimited endurance.",related:["Spintronics","GMR","Berry Phase"]},
  {key:"gaa-transistor",title:"Gate-All-Around (GAA) Transistor",level:"grad",def:"A MOSFET where the gate wraps entirely around the channel (nanosheet or nanowire), giving superior electrostatic control vs. FinFET — enabling scaling below 5 nm while controlling short-channel effects. Samsung introduced GAA (\"MBCFET\") at 3 nm node in 2022; Intel's RibbonFET followed.",related:["Silicon Photonics","Spintronics","MRAM"]},
  {key:"bessel-functions",title:"Bessel Functions",level:"grad",def:"Solutions Jₙ(r) and Yₙ(r) of Bessel's ODE r²y″+ry′+(r²−n²)y=0. Arise in wave problems with cylindrical/spherical symmetry. In step-index optical fiber, the modal field is Jₙ(ur) inside and Kₙ(wr) outside the core; single-mode condition: V = (2πa/λ)NA < 2.405 (first zero of J₀).",related:["Poincaré Sphere (Optics)","Silicon Photonics","Frequency Analysis"]},
  {key:"poincare-sphere-optics",title:"Poincaré Sphere (Optics)",level:"grad",def:"A unit sphere representing all polarization states of a monochromatic electromagnetic wave. North/south poles: right/left circular; equator: linear. Waveplates perform rotations; polarizers project. Isomorphic to the Bloch sphere for a qubit — polarization qubits are the optical realization of spin-½.",related:["Bloch Sphere","Bessel Functions","Berry Phase"]},
  {key:"silicon-photonics",title:"Silicon Photonics",level:"grad",def:"Integrated photonic devices — waveguides, Mach–Zehnder modulators, ring resonators, Ge photodetectors — fabricated in standard silicon CMOS. Enables chip-scale optical interconnects for data centers (400G–1.6T per lambda), co-packaged optics with AI accelerators, LiDAR, and photonic quantum computing.",related:["Bessel Functions","Optical Tweezers","GAA Transistor"]},

  // ── COSMOLOGY/SPECULATIVE ──
  {key:"ccc-aeons",title:"CCC Aeons",level:"res",def:"In Penrose's Conformal Cyclic Cosmology, the universe cycles through an infinite sequence of aeons. Each aeon's far future (massless radiation, evaporated black holes) is conformally equivalent to the next aeon's Big Bang — because massless particles don't perceive time. Penrose claims CCC leaves observational imprints (Hawking points) in the CMB.",related:["Weyl Curvature","Penrose Diagram","Hawking Radiation"]},
  {key:"penrose-diosi-or",title:"Penrose–Diósi Objective Reduction",level:"res",def:"The hypothesis that quantum superpositions collapse (\"objective reduction\") when the gravitational self-energy of the superposition ΔE_grav ≈ ℏ/τ, where τ is the collapse timescale. Gravity causes wavefunction collapse — a concrete, falsifiable proposal that links quantum mechanics and general relativity.",related:["Wavefunctions","Weyl Curvature","Vacuum Energy"]},

  // ── CATEGORY THEORY ──
  {key:"functors",title:"Functors",level:"grad",def:"Structure-preserving maps F: 𝒞 → 𝒟 between categories: F sends objects to objects and morphisms to morphisms, preserving composition and identity. Examples: homology Hₙ: Top → Ab (transforms spaces into abelian groups); fundamental group π₁: Top → Grp; and the free functor Free: Set → Grp.",related:["Toposes","Sheaves","Chern Classes"]},
  {key:"toposes",title:"Toposes",level:"res",def:"A category generalizing the category of sets, equipped with a \"subobject classifier\" Ω playing the role of truth values. Grothendieck toposes (sheaves on a Grothendieck site) unify algebraic geometry, logic, and topology. Their internal logic is intuitionistic — they model constructive mathematics.",related:["Functors","Sheaves","Closed vs Exact Forms"]},
  {key:"sheaves",title:"Sheaves",level:"res",def:"A sheaf on a space X assigns data F(U) to each open set U, with restriction maps: global data restricts to local data; local data agreeing on overlaps glues uniquely. Sheaves are the natural framework for cohomology, D-modules, and the Penrose transform. The derived category of sheaves encodes the topology of X.",related:["Toposes","Functors","Chern Classes"]},

  // ── EXPERIMENTAL FRONTIERS (53–60) ──
  {key:"high-harmonic-generation",title:"High-Harmonic Generation (HHG)",level:"grad",def:"A nonlinear process where intense laser pulses (10¹⁴–10¹⁵ W/cm²) drive electrons through a three-step cycle: (1) tunnel ionisation, (2) acceleration in the laser field, (3) recollision with the parent ion, emitting XUV photons at odd harmonics of the driving frequency. HHG is the primary source of attosecond pulses. Cutoff energy: ℏω_cutoff = Ip + 3.17 Up.",related:["Keldysh Parameter","ADK Rate","Attosecond Pulse"]},
  {key:"keldysh-parameter",title:"Keldysh Parameter",level:"grad",def:"γ = √(Ip / 2Up), where Ip is the ionisation potential and Up = e²E₀²/4mω² is the ponderomotive energy. γ ≫ 1: multiphoton regime (weak field); γ ≪ 1: tunnel ionisation regime (strong field). The transition between regimes governs whether HHG and attosecond science is accessible.",related:["High-Harmonic Generation","ADK Rate","Attosecond Pulse"]},
  {key:"adk-rate",title:"ADK Ionisation Rate",level:"res",def:"Ammosov-Delone-Krainov (1986) formula for the tunnel ionisation rate of atoms in a strong laser field: W ∝ exp(−2(2Ip)^(3/2) / 3E), where E is the electric field strength. The exponential dependence on field strength confines ionisation to the peaks of the laser cycle, producing attosecond bursts.",related:["Keldysh Parameter","High-Harmonic Generation"]},
  {key:"paul-trap",title:"Paul Trap",level:"grad",def:"An ion trap using oscillating radiofrequency electric fields to confine charged particles in free space (Wolfgang Paul, Nobel 1989). The quadrupole potential V(x,y,t) = (U + V_RF cos(Ωt))(x²−y²)/r₀² creates stable Mathieu-equation trajectories. Secular motion frequency: ω_sec ≈ qV_RF/(√2 mΩ r₀²). The basis for all trapped-ion quantum computers.",related:["Jaynes-Cummings Model","Wigner Function"]},
  {key:"jaynes-cummings-model",title:"Jaynes-Cummings Model",level:"grad",def:"Exact quantum model of a two-level atom coupled to a single mode of the quantised radiation field: H = ℏωa†a + ℏω₀σ_z/2 + ℏg(a†σ₋ + aσ₊). Produces vacuum Rabi splitting 2g and Rabi oscillations at frequency Ω_n = 2g√(n+1). Predicts quantum collapses and revivals — direct evidence of field quantisation.",related:["Paul Trap","Wigner Function","Rabi Oscillations"]},
  {key:"wigner-function",title:"Wigner Function",level:"grad",def:"A quasi-probability distribution W(x,p) in phase space representing a quantum state ρ: W(x,p) = (1/πℏ)∫⟨x−y|ρ|x+y⟩ e^(2ipy/ℏ) dy. W can be negative (a signature of non-classicality). Measured experimentally via optical homodyne tomography. Cat states produce oscillating negative fringes between the two positive lobes.",related:["Jaynes-Cummings Model","Paul Trap"]},
  {key:"pmns-matrix",title:"PMNS Matrix",level:"grad",def:"Pontecorvo-Maki-Nakagawa-Sakata unitary matrix U relating neutrino mass eigenstates (ν₁,ν₂,ν₃) to flavour eigenstates (νe,νμ,ντ): |να⟩ = Σᵢ U*αᵢ |νᵢ⟩. Parameterised by three mixing angles (θ₁₂,θ₁₃,θ₂₃) and one CP-violating phase δ. The oscillation probability depends on mass-squared differences Δm²ᵢⱼ = mᵢ² − mⱼ².",related:["Neutrino Oscillations","CP Violation","Mass Hierarchy"]},
  {key:"neutrino-oscillations",title:"Neutrino Oscillations",level:"grad",def:"Quantum interference between neutrino mass eigenstates with different de Broglie wavelengths leads to time-varying flavour probabilities. P(να→νβ) depends on L/E (baseline over energy) and Δm²: P ≈ sin²(2θ) sin²(1.267 Δm² L/E). Discovered by Super-Kamiokande (atmospheric, 1998) and SNO (solar, 2001). Proved neutrinos have mass. 2015 Nobel.",related:["PMNS Matrix","CP Violation"]},
  {key:"anomalous-magnetic-moment",title:"Anomalous Magnetic Moment",level:"grad",def:"The gyromagnetic ratio g of a spin-1/2 particle deviates from the Dirac prediction g=2 due to quantum loop corrections: aμ = (g−2)/2. For the muon, aμ = 116 592 059(22) × 10⁻¹¹ (SM theory). Fermilab E989 (2023) measures aμ = 116 592 055(24) × 10⁻¹¹. The ~5σ tension hints at contributions from undiscovered particles — BSM physics.",related:["Feynman Diagrams","Vacuum Energy","Standard Model"]},
  {key:"lawson-criterion",title:"Lawson Criterion",level:"grad",def:"Minimum condition for net fusion energy gain: the triple product nτT ≥ nτT_crit. For DT fusion, the ignition threshold is nτT ≈ 3×10²¹ m⁻³ s keV at T ≈ 10–20 keV. n is plasma density, τ is energy confinement time, T is ion temperature. NIF achieved Q>1 (3.15 MJ out / 2.05 MJ in) in December 2022 using inertial confinement.",related:["Nuclear Fusion","Rayleigh-Taylor Instability"]},
  {key:"rayleigh-taylor-instability",title:"Rayleigh-Taylor Instability",level:"grad",def:"Hydrodynamic instability at the interface between a dense fluid accelerated into a lighter one (or vice versa). Growth rate: σ = √(Akg), where A = (ρ₂−ρ₁)/(ρ₂+ρ₁) is the Atwood number and k is wavenumber. In ICF hohlraum implosions, RT mixing of cold ablator into the hot spot limits compression and is the primary obstacle to ignition.",related:["Lawson Criterion","Nuclear Fusion"]},
  {key:"cosmological-constant",title:"Cosmological Constant Λ",level:"grad",def:"Einstein's Λ term in the field equations acts as a constant vacuum energy density ρ_Λ = Λc²/8πG, with equation of state w = −1. Observationally, Λ drives accelerating expansion: discovered via Type Ia SN distance moduli in 1998 (Nobel 2011). Λ constitutes ~68% of the total energy density of the universe, yet its theoretical value remains unexplained (120-order-of-magnitude fine-tuning problem).",related:["Hubble Tension","Scale Factor","Vacuum Energy"]},
  {key:"hubble-tension",title:"Hubble Tension",level:"grad",def:"A ~5σ discrepancy between early-universe determinations of H₀ (Planck CMB: 67.4±0.5 km/s/Mpc) and late-universe distance ladder measurements (SH0ES Cepheid+SN Ia: 73.0±1.0 km/s/Mpc). Neither systematic errors nor statistical flukes currently explain the gap. Possible resolutions include early dark energy, extra relativistic species, or modified gravity.",related:["Cosmological Constant Λ","Scale Factor","Type Ia Supernovae"]},
  {key:"type-ia-supernovae",title:"Type Ia Supernovae",level:"ug",def:"Thermonuclear explosions of white dwarfs near the Chandrasekhar mass (~1.4 M☉). Their peak luminosity correlates tightly with the light-curve width (Phillips relation), making them standardisable candles with ~7% distance precision. Used to discover dark energy (1998) via the distance modulus μ = 5 log₁₀(dL/10 pc). 2011 Nobel Prize.",related:["Hubble Tension","Cosmological Constant Λ"]},
  {key:"edwards-anderson-model",title:"Edwards-Anderson Model",level:"grad",def:"Prototype spin glass model (1975): Ising spins on a lattice with quenched random couplings J_ij drawn from a symmetric distribution (e.g., Gaussian). The EA order parameter q_EA = [⟨Sᵢ⟩²_t]_J measures broken ergodicity — spins freeze in random directions below T_g. The competition between ferromagnetic and antiferromagnetic bonds creates geometric frustration.",related:["Parisi RSB","Replica Method","Frustration"]},
  {key:"parisi-rsb",title:"Parisi Replica Symmetry Breaking",level:"res",def:"Giorgio Parisi's 1979–1983 solution to the Sherrington-Kirkpatrick mean-field spin glass: the order parameter becomes a function q(x) on [0,1], reflecting infinitely many pure states arranged in an ultrametric tree. The Parisi free energy functional F[q(x)] is obtained by hierarchical RSB. The 2021 Nobel recognised this as a foundational contribution to complex systems physics.",related:["Edwards-Anderson Model","Replica Method","P(q) Distribution"]},
  {key:"trapped-surface",title:"Trapped Surface",level:"grad",def:"A compact, orientable, spacelike 2-surface where both the ingoing and outgoing null normal congruences have negative expansion (θ < 0). Penrose's 1965 theorem: if spacetime satisfies the null energy condition and contains a trapped surface, at least one future-directed null geodesic is incomplete — a singularity is inevitable. This was the first purely topological proof of singularity formation.",related:["Raychaudhuri Equation","Penrose Diagram","Event Horizon"]},
  {key:"raychaudhuri-equation",title:"Raychaudhuri Equation",level:"grad",def:"Evolution equation for the expansion θ of a congruence of null or timelike geodesics: dθ/dλ = −θ²/2 − σ_μν σ^μν + ω_μν ω^μν − R_μν k^μ k^ν. Under the Null Energy Condition (R_μν k^μ k^ν ≥ 0) and zero rotation, gravity always focuses geodesic bundles (dθ/dλ ≤ 0 if θ ≤ 0). Completing the proof of the Penrose singularity theorem.",related:["Trapped Surface","Penrose Diagram","General Relativity"]},
  {key:"penrose-diagram",title:"Penrose Diagram",level:"grad",def:"A conformal (Carter-Penrose) diagram compresses all of spacetime into a finite rectangle while preserving causal structure. Null geodesics travel at ±45°. Timelike and spacelike infinities (i±, i⁰) and null infinities (ℐ±) are represented as finite points/lines. The Schwarzschild black hole Penrose diagram shows the event horizon, singularity, and the full maximally-extended Kruskal spacetime.",related:["Trapped Surface","Raychaudhuri Equation","Event Horizon"]}
];
